#include <unordered_set>
#include <constants.h>

const Position B_QUEEN_POS = E4;
const std::array<PieceType, 64> B_QUEEN_BOARD = {
	NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, 	
	NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, 	
	NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, 	
	NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, 	
	NONE, NONE, NONE, NONE, B_QUEEN, NONE, NONE, NONE, 	
	NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, 	
	NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, 	
	NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE
};

const std::unordered_set<Position> B_QUEEN_ALL_MOVES = {
	A8, E8,
	B7, E7, H7,
	C6, E6, G6,
	D5, E5, F5,
	A4, B4, C4, D4, F4, G4, H4,
	D3, E3, F3,
	C2, E2, G2,
	B1, E1, H1
};

const Position B_BISHOP_POS = D4;
const std::array<PieceType, 64> B_BISHOP_BOARD = {
	NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, 	
	NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, 	
	NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, 	
	NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, 	
	NONE, NONE, NONE, B_BISHOP, NONE, NONE, NONE, NONE, 	
	NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, 	
	NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, 	
	NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE
};

const std::unordered_set<Position> B_BISHOP_ALL_MOVES = {
	H8,
	A7, G7,
	B6, F6,
	C5, E5,
	C3, E3,
	B2, F2,
	A1, G1
};

const Position B_KNIGHT_POS = D5;
const std::array<PieceType, 64> B_KNIGHT_BOARD = {
	NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, 	
	NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, 	
	NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, 	
	NONE, NONE, NONE, B_KNIGHT, NONE, NONE, NONE, NONE, 	
	NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, 	
	NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, 	
	NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, 	
	NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE
};

const std::unordered_set<Position> B_KNIGHT_ALL_MOVES = {
	C7, E7,
	B6, F6,
	B4, F4,
	C3, E3
};

const Position B_ROOK_POS = E5;
const std::array<PieceType, 64> B_ROOK_BOARD = {
	NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, 	
	NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, 	
	NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, 	
	NONE, NONE, NONE, NONE, B_ROOK, NONE, NONE, NONE, 	
	NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, 	
	NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, 	
	NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, 	
	NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE
};

const std::unordered_set<Position> B_ROOK_ALL_MOVES = {
	E8, E7, E6,
	A5, B5, C5, D5, F5, G5, H5,
	E4, E3, E2, E1
};


const Position B_KING_POS = C4;
const std::array<PieceType, 64> B_KING_BOARD = {
	NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, 	
	NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, 	
	NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, 	
	NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, 	
	NONE, NONE, B_KING, NONE, NONE, NONE, NONE, NONE, 	
	NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, 	
	NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, 	
	NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE
};

const std::unordered_set<Position> B_KING_ALL_MOVES = {
	B5, C5, D5,
	B4, D4,
	B3, C3, D3
};


const Position B_PAWN_POS = F4;
const std::array<PieceType, 64> B_PAWN_BOARD = {
	NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, 	
	NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, 	
	NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, 	
	NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, 	
	NONE, NONE, NONE, NONE, NONE, B_PAWN, NONE, NONE, 	
	NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, 	
	NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, 	
	NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE
};

const std::unordered_set<Position> B_PAWN_ALL_MOVES = {
	F3
};
const Position B_KNIGHT_SIDE1_POS = B7;
const std::array<PieceType, 64> B_KNIGHT_SIDE1_BOARD = {
	NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, 	
	NONE, B_KNIGHT, NONE, NONE, NONE, NONE, NONE, NONE, 	
	NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, 	
	NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, 	
	NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, 	
	NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, 	
	NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, 	
	NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE
};
const std::unordered_set<Position> B_KNIGHT_SIDE1_ALL_MOVES = {
	D8,
	D6,
	A5, C5
};
const Position B_KING_SIDE1_POS = A8;
const std::array<PieceType, 64> B_KING_SIDE1_BOARD = {
	B_KING, NONE, NONE, NONE, NONE, NONE, NONE, NONE, 	
	NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, 	
	NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, 	
	NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, 	
	NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, 	
	NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, 	
	NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, 	
	NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE
};
const std::unordered_set<Position> B_KING_SIDE1_ALL_MOVES = {
	B8,
	A7,B7
};

const Position B_PAWN_SIDE1_POS = A7;
const std::array<PieceType, 64> B_PAWN_SIDE1_BOARD = {
	NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, 	
	B_PAWN, NONE, NONE, NONE, NONE, NONE, NONE, NONE, 	
	NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, 	
	NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, 	
	NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, 	
	NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, 	
	NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, 	
	NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE
};
const std::unordered_set<Position> B_PAWN_SIDE1_ALL_MOVES = {
	A6, A5
};
