#CC=g++-4.2
#
#a.out: main.o SerialComm.o
#	g++ main.o SerialComm.o -lboost_system -lboost_filesystem -lboost_serialization -lpthread -std=c++11
#
#main.o: main.cpp
#	g++ -c -std=c++11 main.cpp
#
#SerialComm.o: SerialComm.cpp SerialComm.hpp
#	g++ -c -std=c++11 SerialComm.cpp

default: build

build:
	g++ -o chess.out chess.cpp -std=c++11
